// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: facts.sql

package database

import (
	"context"
	"time"
)

const createFact = `-- name: CreateFact :exec
INSERT INTO facts (cik, category, tag, label, description, units, end_d, value, fiscal_year, fiscal_period, form)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
    )
ON CONFLICT ON CONSTRAINT facts_pkey DO NOTHING
`

type CreateFactParams struct {
	Cik          int32
	Category     string
	Tag          string
	Label        string
	Description  string
	Units        string
	EndD         time.Time
	Value        string
	FiscalYear   int32
	FiscalPeriod string
	Form         string
}

func (q *Queries) CreateFact(ctx context.Context, arg CreateFactParams) error {
	_, err := q.db.ExecContext(ctx, createFact,
		arg.Cik,
		arg.Category,
		arg.Tag,
		arg.Label,
		arg.Description,
		arg.Units,
		arg.EndD,
		arg.Value,
		arg.FiscalYear,
		arg.FiscalPeriod,
		arg.Form,
	)
	return err
}
