// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Company struct {
	Cik      int32
	Name     string
	Ticker   string
	Exchange string
}

type Ohlc struct {
	Ticker string
	Ts     time.Time
	Open   string
	High   string
	Low    string
	Close  string
	Volume string
}
