// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ohlc.sql

package database

import (
	"context"
	"time"
)

const createTickerTimestamp = `-- name: CreateTickerTimestamp :one
INSERT INTO ohlc (ticker, ts, open, high, low, close, volume)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
    )
ON CONFLICT ON CONSTRAINT ohlc_pkey DO UPDATE SET 
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume
RETURNING ticker, ts, open, high, low, close, volume
`

type CreateTickerTimestampParams struct {
	Ticker string
	Ts     time.Time
	Open   string
	High   string
	Low    string
	Close  string
	Volume string
}

func (q *Queries) CreateTickerTimestamp(ctx context.Context, arg CreateTickerTimestampParams) (Ohlc, error) {
	row := q.db.QueryRowContext(ctx, createTickerTimestamp,
		arg.Ticker,
		arg.Ts,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i Ohlc
	err := row.Scan(
		&i.Ticker,
		&i.Ts,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
	)
	return i, err
}
