services:
  fingator:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:14.15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 7
      start_period: 10s
      timeout: 10s
    networks:
      - app-network

  admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  #  grafana:
  #    image: grafana/grafana-enterprise
  #    container_name: grafana
  #    restart: unless-stopped
  #    ports:
  #      - '3000:3000'
  #    volumes:
  #      - grafana-storage:/var/lib/grafana
  #volumes:
  #  grafana-storage: {}
