services:
  db:
    image: postgres:14.15
    env_file:
      - .env
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 7
      start_period: 10s
      timeout: 10s
    networks:
      - app-network

  admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

  fingator:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - app-network
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  app-network:
    driver: bridge

volumes:
  grafana-storage: {}
