services:
  fingator:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: ["./fingator"]

  db:
    image: postgres:14.15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 7
      start_period: 10s
      timeout: 10s

  #  grafana:
  #    image: grafana/grafana-enterprise
  #    container_name: grafana
  #    restart: unless-stopped
  #    ports:
  #      - '3000:3000'
  #    volumes:
  #      - grafana-storage:/var/lib/grafana
  #volumes:
  #  grafana-storage: {}
